<?php 
$url = new Model_Core_Url();
?>
<header>
	<a href=<?php echo $url->getUrl('grid','product'); ?>>Product</a>
	<a href=<?php echo $url->getUrl('grid','category'); ?>>Category</a>
	<a href=<?php echo $url->getUrl('grid','customer'); ?>>Customer</a>
	<a href=<?php echo $url->getUrl('grid','vendor'); ?>>Vendor</a>
	<a href=<?php echo $url->getUrl('grid','salesman'); ?>>Salesman</a>
	<a href=<?php echo $url->getUrl('grid','shipping'); ?>>Shipping Method</a>
	<a href=<?php echo $url->getUrl('grid','payment'); ?>>Payment Method</a>
</header>
<?php require_once 'message.phtml';?>