<?php $product = $this->getData('product');?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>">
	<table>
		<tr>
			<th>Manage Product</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>SKU Id</td>
			<td><input type="text" name="product[sku_id]" value="<?php echo $product->sku_id; ?>"></td>
		</tr>
		<tr>
			<td>Cost</td>
			<td><input type="number" name="product[cost]" value="<?php echo $product->cost; ?>"></td>
		</tr>
		<tr>
			<td>Price</td>
			<td><input type="number" name="product[price]" value="<?php echo $product->price; ?>"></td>
		</tr>
		<tr>
			<td>Quantity</td>
			<td><input type="number" name="product[quantity]" value="<?php echo $product->quantity; ?>"></td>
		</tr>
		<tr>
			<td>Description</td>
			<td><textarea name="product[description]"><?php echo $product->description; ?></textarea></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="product[status]">
					<?php foreach (Ccc::getModel('Product_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key; ?>" <?php echo ($product->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Color</td>
			<td><input type="text" name="product[color]" value="<?php echo $product->color; ?>"></td>
		</tr>
		<tr>
			<td>Material</td>
			<td><input type="text" name="product[material]" value="<?php echo $product->material; ?>"></td>
		</tr>
	</table>
</form>