<?php $products = $this->prepareData();?>
<table>
	<tr>
		<th colspan="10">Manage Products</th>
		<th colspan="3"><a href="<?php echo $this->getUrl('add'); ?>">Add Product</a></th>
	</tr>
	<tr>
		<td>Product Id</td>
		<td>SKU Id</td>
		<td>Cost</td>
		<td>Price</td>
		<td>Quantity</td>
		<td>Description</td>
		<td>Status</td>
		<td>Color</td>
		<td>Material</td>
		<td>Created At</td>
		<td>Updated At</td>
		<td>Show Images</td>
		<td>EDIT</td>
		<td>DELETE</td>
	</tr>
	<?php if(!$products->getData()): ?>
	<tr>
		<td colspan="13">No Record Found</td>
	</tr>
	<?php else: ?>
	<?php foreach ($products->getData() as $product): ?>
	<tr>
		<td><?php echo $product->product_id; ?></td>
		<td><?php echo $product->sku_id; ?></td>
		<td><?php echo $product->cost; ?></td>
		<td><?php echo $product->price; ?></td>
		<td><?php echo $product->quantity; ?></td>
		<td><?php echo $product->description; ?></td>
		<td><?php echo $product->getStatusText(); ?></td>
		<td><?php echo $product->color; ?></td>
		<td><?php echo $product->material; ?></td>
		<td><?php echo $product->created_at; ?></td>
		<td><?php echo $product->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('grid','product_media',['product_id'=>$product->product_id]); ?>">Show Images</a></td>
		<td><a href="<?php echo $this->getUrl('edit',null,['product_id'=>$product->product_id]); ?>">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete',null,['product_id'=>$product->product_id]); ?>">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>