<div>
<form id="import_product" method="POST" action="index.php?c=product&a=importProduct" enctype='multipart/form-data'>
	<table>
		<tr>
			<td>Uplaod file</td>
		</tr>
		<tr>
			<td>
				<input name = 'csv' type="file" />
			</td>
		</tr>
		<tr>
			<td>
				<input type="submit" value = 'Import'>
			</td>
		</tr>
	</table>
</form>
</div>
 <!-- accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" -->
 <!-- onclick="ajax.setUrl('<?php //echo $this->getUrl('importProduct',null,null,true); ?>').setForm('import_product').setMethod('POST').call()" -->