<?php $shipping = $this->prepareData()->getData('shipping');?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>">
	<table>
		<tr>
			<th>Manage Shipping</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name="shipping[name]" value="<?php echo $shipping->name; ?>"></td>
		</tr>	
		<tr>
			<td>Amount</td>
			<td><input type="number" name="shipping[amount]" value="<?php echo $shipping->amount; ?>"></td>
		</tr>	
		<tr>
			<td>Status</td>
			<td>
				<select name="shipping[status]">
					<?php foreach (Ccc::getModel('Shipping_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key;?>" <?php echo ($key == $shipping->getStatus()) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>	
	</table>
</form>
