<?php $shippings = $this->prepareData();?>
<table>
	<tr>
		<th colspan="5">Manage Shipping</th>
		<th colspan="3"><a href="<?php echo $this->getUrl('add'); ?>">Add Shipping</a></th>
	</tr>
	<tr>
		<td>Shipping Id</td>
		<td>Name</td>
		<td>Amount</td>
		<td>Status</td>
		<td>Created At</td>
		<td>Updated At</td>
		<td>EDIT</td>
		<td>DELETE</td>
	</tr>
	<?php if (!$shippings->getData()) : ?>
	<tr>
		<td>No Data Found!!</td>
	</tr>
	<?php else : ?>
	<?php foreach ($shippings->getData() as $shipping) : ?>
	<tr>
		<td><?php echo $shipping->shipping_id; ?></td>
		<td><?php echo $shipping->name; ?></td>
		<td><?php echo $shipping->amount; ?></td>
		<td><?php echo $shipping->getStatusText(); ?></td>
		<td><?php echo $shipping->created_at; ?></td>
		<td><?php echo $shipping->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit',null,['shipping_id'=>$shipping->shipping_id]); ?>">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete',null,['shipping_id'=>$shipping->shipping_id]); ?>">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>