<?php 
$data = $this->prepareData();
$salesmanPrices = $data['salesman_prices'];
$salesmen = $data['salesmen'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action=<?php echo $this->getUrl('update',null,null); ?>>
		<table border="2px" width="100%">
			<tr>
				<td>Salesman : 
					<select onchange="changeSalesman(this.value)">
						<option>select salesman</option>
						<?php foreach ($salesmen->getData() as $salesman) : ?>
						<option value="<?php echo $salesman->salesman_id; ?>" <?php if($_GET['salesman_id'] == $salesman->salesman_id){ echo 'selected';} ?>><?php echo $salesman->first_name; ?></option>
						<?php endforeach;?>
					</select>
				</td>
				<td><input type="submit" value="UPDATE"></td>
			</tr>
		</table>
		<table border="2px" width="100%">
			<tr>
				<th>Product ID</th>
				<th>SKU</th>
				<th>COST</th>
				<th>PRICE</th>
				<th>S-PRICE</th>
				<th>REMOVE</th>
			</tr>
			<?php foreach ($salesmanPrices->getData() as $prices) : ?>
			<tr>
				<td><?php echo $prices->product_id; ?></td>
				<td><?php echo $prices->sku_id; ?></td>
				<td><?php echo $prices->cost; ?></td>
				<td><?php echo $prices->price; ?></td>
				<td><input type="number" name = "salesman_price[<?php echo $prices->product_id; ?>]" value=<?php echo $prices->salesman_price; ?>></td>
				<td>
					<?php if ($prices->entity_id) { ?>
					<a href=<?php echo $this->getUrl('delete',null,['entity_id'=>$prices->entity_id]); ?>>REMOVE</a>
					<?php } ?>
				</td>
			</tr>	
			<?php endforeach;?>
		</table>
	</form>
	<script type="text/javascript">
		function changeSalesman(salesman_id) {
			window.location.href = "index.php?c=salesman_price&a=grid&salesman_id="+salesman_id;  
		}
	</script>
</body>
</html>