<?php $admin = $this->prepareData()->getData('admin');?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>">
	<table>
		<tr>
			<th>Manage Admin</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name="admin[name]" value="<?php echo $admin->name; ?>"></td>
		</tr>	
		<tr>
			<td>Email</td>
			<td><input type="text" name="admin[email]" value="<?php echo $admin->email; ?>"></td>
		</tr>
		<tr>
			<td>Password</td>
			<td><input type="password" name="admin[password]" value="<?php echo $admin->password; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="admin[status]">
					<?php foreach (Ccc::getModel('Admin_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key;?>" <?php echo ($key == $admin->getStatus()) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>	
	</table>
</form>
