<?php $admins = $this->prepareData();?>
<?php $pager = $this->getPager(0,1); ?>
<?php $this->getLayout()->creatBlock('Core_Pager')->setPager($pager)->render(); ?>
<table class="table table-bordered border-primary ">
	<tr>
		<th colspan="5">Manage Admin</th>
		<th colspan="3"><a onclick="ajax.setUrl('<?php echo $this->getUrl('add'); ?>').call()">Add Admin</a></th>
	</tr>
	<tr>
		<td>Admin Id</td>
		<td>Name</td>
		<td>E-mail</td>
		<td>Status</td>
		<td>Created At</td>
		<td>Updated At</td>
		<td>EDIT</td>
		<td>DELETE</td>
	</tr>
	<?php if (!$admins) : ?>
	<tr>
		<td>No Data Found!!</td>
	</tr>
	<?php else : ?>
	<?php foreach ($admins->getData() as $admin) : ?>
	<tr>
		<td><?php echo $admin->admin_id; ?></td>
		<td><?php echo $admin->name; ?></td>
		<td><?php echo $admin->email; ?></td>
		<td><?php echo $admin->getStatusText(); ?></td>
		<td><?php echo $admin->created_at; ?></td>
		<td><?php echo $admin->updated_at; ?></td>
		<td><a onclick="ajax.setUrl('<?php echo $this->getUrl('edit',null,['admin_id'=>$admin->admin_id]); ?>').call()">EDIT</a></td>
		<td><a onclick="ajax.setUrl('<?php echo $this->getUrl('delete',null,['admin_id'=>$admin->admin_id]); ?>').call()">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>