<?php 
$attribute = $this->prepareData()->getData('attribute');
$options = $this->getOptions();
$entities = $this->getEntities();
?>
<form method="POST" action="" id="eav_attribute">
	<table>
		<tr>
			<th>Manage Attribute</th>
			<th><input type="button" value="Save" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setMethod('POST').setForm('eav_attribute').call()"></th>
		</tr>
		<tr>
			<td>Entity Type Id</td>
			<td>
				<select name="attribute[entity_type_id]">
					<?php foreach ($entities as $entity) : ?>
						<option value="<?php echo $entity['entity_type_id']; ?>" <?php echo ($entity['entity_type_id'] == $attribute->entity_type_id) ? 'selected' : ''; ?>><?php echo $entity['name']; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name="attribute[name]" value="<?php echo $attribute->name; ?>"></td>
		</tr>
		<tr>
			<td>Code</td>
			<td><input type="text" name="attribute[code]" value="<?php echo $attribute->code; ?>"></td>
		</tr>
		<tr>
			<td>Input type</td>
			<td>
				<select name="attribute[input_type]" onchange="changeOption(this)">
					<option value="text">Text</option>
					<option value="textBox">Text Box</option>
					<option value="select">Select</option>
					<option value="radio">Radio</option>
					<option value="checkBox">Check Box</option>
					<option value="multipleSelect">Multiple Select</option>
				</select>
			</td>
		</tr>
		<tr id="inputTypeOptions" style="display: none;">
			<td>Options</td>
			<td>
				<table id="optionTable">
					<tr>
						<td colspan="2"><input type="button" name="add" id="add" value="Add Option"></td>
					</tr>
					<?php if (!$options) :?>
					<tr class="optionInputRow">
						<td>Add Options</td>
					</tr>
					<?php else : ?>
					<?php foreach ($options->getData() as $option) : ?>
					<tr class="optionInputRow">
						<td><input type="text" name="attribute[option][exist][<?php echo $option->option_id; ?>]" value="<?php echo $option->name; ?>"></td>
						<td><input type="button" name="remove" class="remove" value="Remove"></td>
					</tr>
					<?php endforeach; ?>
					<?php endif; ?>
				</table>
			</td>
		</tr>
		<tr>
			<td>Backend Type</td>
			<td><input type="text" name="attribute[backend_type]" value="<?php echo $attribute->backend_type; ?>"></td>
		</tr>
		<tr>
			<td>Backend Model</td>
			<td><textarea name="attribute[backend_model]"><?php echo $attribute->backend_model; ?></textarea></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="attribute[status]">
					<?php foreach (Ccc::getModel('Eav_Attribute_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key; ?>" <?php echo ($attribute->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>
	</table>
</form>
<table id="optionInputRowTable" style="display:none;">
	<tr class="optionInputRow">
		<td><input type="text" name="attribute[option][new][]"></td>
		<td><input type="button" name="remove" class="remove" value="Remove"></td>
	</tr>
</table>
<script type="text/javascript">
$('#inputTypeOptions').hide();
function changeOption(object) {
	var inputType = $(object);
	if (inputType.val() == 'radio' || inputType.val() == 'checkBox' || inputType.val() == 'select' || inputType.val() == 'multiSelect') {
		$('#inputTypeOptions').show();
	}else{
		$('#inputTypeOptions').hide();
	}
}

$('#add').click(function () {
	var row = $('#optionInputRowTable .optionInputRow').clone();
	$('#optionTable tbody').append(row);
});

$('#optionTable').on('click', '.remove', function() {
    var parentRow = $(this).closest('tr');
    parentRow.remove();
});
</script>