<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<div>
		<form method="POST" action=<?php echo $this->getUrl('insert',null,null); ?> enctype="multipart/form-data">
			<table>
				<tr>
					<td>ADD IMAGE</td>
				</tr>
				<tr>
					<td>Name</td>
					<td><input type="text" name="name"></td>
				</tr>
				<tr>
					<td>Browse Image</td>
					<td><input type="file" name="image"></td>
				</tr>
				<tr>
					<td><input type="submit"></td>
				</tr>
			</table>
		</form>
	</div>
</body>
</html>