<!DOCTYPE html>
<html>
<?php $this->getChild('head')->render(); ?>
<body>
	<table width="100%" border="1px solid bLack" style="text">
		<tr height="100">
			<td><?php $this->getChild('header')->render(); ?></td>
		</tr>
		<tr height="40">
			<td><?php $this->getChild('message')->render(); ?></td>
		</tr>
		<tr height="250">
			<td><?php $this->getChild('content')->render(); ?></td>
		</tr>
		<tr height="50">
			<td><?php $this->getChild('footer')->render(); ?></td>
		</tr>
	</table>
</body>
</html>