<?php 
$customer = $this->getData('customer');
$address = $this->getData('address');
?>
<form method="POST" action=<?php echo $this->getUrl('save',null,['customer_id'=>$customer->customer_id,'address_id'=>$address->address_id],true); ?>>
	<div class="head_container">
		<h2 class="edit_heading">Customer Data</h2>
		<a class="cancel_link" type="cancel" href=<?php echo $this->getUrl('grid',null,null,true); ?>>CANCEL</a>
		<input class="save_link" type="submit" value="Save">
	</div>
	<div class="tabel_container">
		<table>
			<tr>
				<th>CUSTOMER INFORMATION</th>
			</tr>
			<tr>
				<td>First Name</td>
				<td> <input type="text" name="customer[first_name]" value=<?php echo $customer->first_name; ?>> </td>
			</tr>
			<tr>
				<td>Last Name</td>
				<td> <input type="text" name="customer[last_name]" value=<?php echo $customer->last_name; ?>> </td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td> <input type="text" name="customer[email]" value=<?php echo $customer->email; ?>> </td>
			</tr>
			<tr>
				<td>Gender</td>
				<td>
					<select name="customer[gender]">
						<option value="male" <?php if($customer->gender == "male") echo "SELECTED";?>>Male</option>
						<option value="female" <?php if($customer->gender == "female") echo "SELECTED";?>>Female</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>Mobile</td>
				<td> <input type="number" name="customer[mobile]" value=<?php echo $customer->mobile; ?>> </td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="customer[status]">
						<?php foreach (Ccc::getModel('Customer_Resource')->getStatusOptions() as $key => $value) : ?>
						<option value="<?php echo $key; ?>" <?php echo ($customer->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
						<?php endforeach;?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Address</td>
				<td><textarea name="address[address]"><?php echo $address->address; ?></textarea></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="address[city]" value=<?php echo $address->city; ?>></textarea></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="address[state]" value=<?php echo $address->state; ?>></textarea></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="address[country]" value=<?php echo $address->country; ?>></textarea></td>
			</tr>
			<tr>
				<td>ZIP Code</td>
				<td><input type="number" name="address[zip_code]" value=<?php echo $address->zip_code; ?>></textarea></td>
			</tr>
		</table>
	</div>
</form>
