<?php 
$customer = $this->getData('customer');
$billingAddress = $this->getData('billing_address');
$shippingAddress = $this->getData('shipping_address');
?>
<form id="customer" method="POST" action="">
	<div class="head_container">
		<h2 class="edit_heading">Customer Data</h2>
		<a class="cancel_link" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,null,true); ?>').call()">CANCEL</a>
		<input class="save_link" type="button" value="Save" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setMethod('POST').setForm('customer').call()">
	</div>
	<div class="tabel_container">
		<table>
			<tr>
				<th colspan="2">CUSTOMER INFORMATION</th>
			</tr>
			<tr>
				<td>First Name</td>
				<td> <input type="text" name="customer[first_name]" value=<?php echo $customer->first_name; ?>> </td>
			</tr>
			<tr>
				<td>Last Name</td>
				<td> <input type="text" name="customer[last_name]" value=<?php echo $customer->last_name; ?>> </td>
			</tr>
			<tr>
				<td>E-mail</td>
				<td> <input type="text" name="customer[email]" value=<?php echo $customer->email; ?>> </td>
			</tr>
			<tr>
				<td>Gender</td>
				<td>
					<select name="customer[gender]">
						<option value="male" <?php if($customer->gender == "male") echo "SELECTED";?>>Male</option>
						<option value="female" <?php if($customer->gender == "female") echo "SELECTED";?>>Female</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>Mobile</td>
				<td> <input type="number" name="customer[mobile]" value=<?php echo $customer->mobile; ?>> </td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="customer[status]">
						<?php foreach (Ccc::getModel('Customer_Resource')->getStatusOptions() as $key => $value) : ?>
						<option value="<?php echo $key; ?>" <?php echo ($customer->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
						<?php endforeach;?>
					</select>
				</td>
			</tr>
			<tr>
				<th colspan="2">Billing Address</th>
			</tr>
			<tr>
				<td>Address</td>
				<td><textarea name="address[billing_address][address]"><?php echo $billingAddress->address; ?></textarea></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="address[billing_address][city]" value=<?php echo $billingAddress->city; ?>></textarea></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="address[billing_address][state]" value=<?php echo $billingAddress->state; ?>></textarea></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="address[billing_address][country]" value=<?php echo $billingAddress->country; ?>></textarea></td>
			</tr>
			<tr>
				<td>ZIP Code</td>
				<td><input type="number" name="address[billing_address][zip_code]" value=<?php echo $billingAddress->zip_code; ?>></textarea></td>
			</tr>

			<tr>
				<th colspan="2">Shipping Address</th>
			</tr>
			<tr>
				<td>Address</td>
				<td><textarea name="address[shipping_address][address]"><?php echo $shippingAddress->address; ?></textarea></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="address[shipping_address][city]" value=<?php echo $shippingAddress->city; ?>></textarea></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="address[shipping_address][state]" value=<?php echo $shippingAddress->state; ?>></textarea></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="address[shipping_address][country]" value=<?php echo $shippingAddress->country; ?>></textarea></td>
			</tr>
			<tr>
				<td>ZIP Code</td>
				<td><input type="number" name="address[shipping_address][zip_code]" value=<?php echo $shippingAddress->zip_code; ?>></textarea></td>
			</tr>
		</table>
	</div>
</form>
