<?php $customeres = $this->prepareData();?>

<div>
	<?php require_once 'View/html/header.phtml'; ?>
</div>
<div class="head_container">
	<h2 class="customer_heading">MANAGE CUSTOMERS</h2>
	<a class="add_customer_link" href=<?php echo $this->getUrl('add',null,null,true); ?>>ADD CUSTOMER</a>
</div>
<div class="tabel_container">
	<table>
		<tr>
			<th>Customer ID</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>E-mail</th>
			<th>Mobile</th>
			<th>Gender</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>Show Address</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php if (!$customeres->getData()) : ?>
		<tr>
			<td colspan="12">No Record Found!!!</td>
		</tr>
		<?php else: ?>
		<?php foreach ($customeres->getData() as $customer) :?>
		<tr>
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->getStatusText(); ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href=<?php echo $this->getUrl('address',null,['customer_id'=>$customer->customer_id],true); ?>>Show Address</a></td>
			<td><a href=<?php echo $this->getUrl('edit',null,['customer_id'=>$customer->customer_id],true); ?>>Edit</a></td>
			<td><a href=<?php echo $this->getUrl('delete',null,['customer_id'=>$customer->customer_id],true); ?>>Delete</a></td>
		</tr>
		<?php endforeach;?>
		<?php endif; ?>
	</table>
</div>
