<?php $payment = $this->prepareData()->getData('payment');?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>">
	<table>
		<tr>
			<th>Manage Payment</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name='payment[name]' value="<?php echo $payment->name; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="payment[status]">
					<?php foreach (Ccc::getModel('Payment_Resource')->getStatusOptions() as $key => $value) : ?>
						<option value="<?php echo $key; ?>" <?php echo ($key == $payment->getStatus()) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
	</table>
</form>