<?php $payments = $this->prepareData();?>
<table>
	<tr>
		<th colspan="4">Manage Payments</th>
		<th colspan="3"><a href="<?php echo $this->getUrl('add'); ?>">Add Payments</a></th>
	</tr>
	<tr>
		<th>Payment Id</th>		
		<th>Name</th>
		<th>Status</th>		
		<th>Created at</th>		
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>
	<?php if (!$payments->getData()) : ?>
	<tr>
		<td>No record Found!!!</td>
	</tr>
	<?php else: ?>
	<?php foreach ($payments->getData() as $payment) : ?>
	<tr>
		<td><?php echo $payment->payment_id; ?></td>		
		<td><?php echo $payment->name; ?></td>		
		<td><?php echo $payment->getStatusText(); ?></td>		
		<td><?php echo $payment->created_at; ?></td>		
		<td><?php echo $payment->updated_at; ?></td>		
		<td><a href="<?php echo $this->getUrl('edit',null,['payment_id'=>$payment->payment_id]) ?>">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete',null,['payment_id'=>$payment->payment_id]) ?>">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>