<?php  $row = $this->getData('category');?>
<?php $attributes = $this->getAttributes(); ?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>" >
	<table>
		<tr>
			<th>Manage Category</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>Parent Id</td>
			<td>
				<select name="category[parent_id]">
					<?php foreach ($row->getParentCategories() as $categoryId => $pathName) : ?>
					<option value="<?php echo $categoryId; ?>"><?php echo $pathName; ?></option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name = 'category[name]' value="<?php echo $row->name; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="category[status]">
					<?php foreach (Ccc::getModel('Category_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key; ?>" <?php echo ($row->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Description</td>
			<td><textarea name="category[description]"><?php echo $row->description; ?></textarea></td>
		</tr>
		<?php if ($attributes) : ?>
		<?php foreach ($attributes->getData() as $attribute) : ?>
		<tr>
			<td><?php echo $attribute->name; ?></td>
			<td>
				<?php $this->getLayout()->creatBlock('Eav_Attribute_InputType')->setAttribute($attribute)->setRow($row)->render(); ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</form>	