<?php  $category = $this->prepareData()->getData('category');?>
<form method="POST" action="<?php echo $this->getUrl('save'); ?>" >
	<table>
		<tr>
			<th>Manage Category</th>
			<th><input type="submit" value="Save"></th>
		</tr>
		<tr>
			<td>Parent Id</td>
			<td>
				<select name="category[parent_id]">
					<?php foreach ($category->getParentCategories() as $categoryId => $pathName) : ?>
					<option value="<?php echo $categoryId; ?>"><?php echo $pathName; ?></option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td><input type="text" name = 'category[name]' value="<?php echo $category->name; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="category[status]">
					<?php foreach (Ccc::getModel('Category_Resource')->getStatusOptions() as $key => $value) : ?>
					<option value="<?php echo $key; ?>" <?php echo ($category->getStatus() == $key) ? 'selected' : ''; ?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>Description</td>
			<td><textarea name="category[description]"><?php echo $category->description; ?></textarea></td>
		</tr>
	</table>
</form>	