<?php $categories = $this->prepareData();?>
<table>
	<tr>
		<th colspan="6">Manage Category</th>
		<th colspan="4"><a href="<?php echo $this->getUrl('add'); ?>">Add Category</a></th>
	</tr>
	<tr>
		<td>Category Id</td>
		<td>Parent Id</td>
		<td>Path</td>
		<td>Name</td>
		<td>Status</td>
		<td>Description</td>
		<td>Created At</td>
		<td>Updated At</td>
		<td>EDIT</td>
		<td>DELETE</td>
	</tr>
	<?php if (!$categories->getData()) : ?>
	<tr>
		<td>No Record Founded!! </td>
	</tr>
	<?php else : ?>
	<?php foreach ($categories->getData() as $category) : ?>
	<tr>
		<td><?php echo $category->category_id; ?></td>
		<td><?php echo $category->parent_id; ?></td>
		<td><?php echo $category->getPathName(); ?></td>
		<td><?php echo $category->name; ?></td>
		<td><?php echo $category->getStatusText(); ?></td>
		<td><?php echo $category->description; ?></td>
		<td><?php echo $category->created_at; ?></td>
		<td><?php echo $category->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit',null,['category_id'=>$category->category_id],true); ?>">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete',null,['category_id'=>$category->category_id],true); ?>">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>
