<?php $rows = $this->getCollection(); ?>
<?php if ($rows) : ?>
<?php $pager = $this->getPager(0,10); ?>
<?php $this->getLayout()->creatBlock('Core_Pager')->setPager($pager)->render(); ?>
<?php endif; ?>
<table class="table table-bordered border-primary ">
	<tr>
		<th><?php echo $this->getTitle(); ?></th>
		<?php foreach ($this->getButtons() as $key => $button) : ?>
		<th><a onclick="ajax.setUrl('<?php echo $this->getUrl($key,null,null,true); ?>').call()" ><?php echo $button['title']; ?></a></th>
		<?php endforeach; ?>
	</tr>
	<tr>
		<?php foreach ($this->getColumns() as $key => $column) : ?>
		<th><?php echo $column['title']; ?></th>		
		<?php endforeach; ?>
		<?php foreach ($this->getActions() as $key => $action) : ?>
		<th><?php echo $action['title']; ?></th>		
		<?php endforeach; ?>
	</tr>
	<?php if (!$rows) : ?>
	<tr>
		<td>No record Found!!!</td>
	</tr>
	<?php else: ?>
	<?php foreach ($rows->getData() as $row) : ?>
	<tr>
		<?php foreach ($this->getColumns() as $key => $column) : ?>
		<td><?php echo $this->getColumnValue($key,$row); ?></td>
		<?php endforeach; ?>
		<?php foreach ($this->getActions() as $key => $action) : ?>
		<td><a onclick="ajax.setUrl('<?php echo $this->getUrl($key,null,[$row->getResource()->getPrimarykey()=>$row->getId()]); ?>').call()"><?php echo $action['title']; ?></a></td>
		<?php endforeach; ?>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>